require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TrafficSourcesController do

  def mock_traffic_source(stubs={})
    @mock_traffic_source ||= mock_model(TrafficSource, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all traffic_sources as @traffic_sources" do
      TrafficSource.stub(:all) { [mock_traffic_source] }
      get :index
      assigns(:traffic_sources).should eq([mock_traffic_source])
    end
  end

  describe "GET show" do
    it "assigns the requested traffic_source as @traffic_source" do
      TrafficSource.stub(:find).with("37") { mock_traffic_source }
      get :show, :id => "37"
      assigns(:traffic_source).should be(mock_traffic_source)
    end
  end

  describe "GET new" do
    it "assigns a new traffic_source as @traffic_source" do
      TrafficSource.stub(:new) { mock_traffic_source }
      get :new
      assigns(:traffic_source).should be(mock_traffic_source)
    end
  end

  describe "GET edit" do
    it "assigns the requested traffic_source as @traffic_source" do
      TrafficSource.stub(:find).with("37") { mock_traffic_source }
      get :edit, :id => "37"
      assigns(:traffic_source).should be(mock_traffic_source)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created traffic_source as @traffic_source" do
        TrafficSource.stub(:new).with({'these' => 'params'}) { mock_traffic_source(:save => true) }
        post :create, :traffic_source => {'these' => 'params'}
        assigns(:traffic_source).should be(mock_traffic_source)
      end

      it "redirects to the created traffic_source" do
        TrafficSource.stub(:new) { mock_traffic_source(:save => true) }
        post :create, :traffic_source => {}
        response.should redirect_to(traffic_source_url(mock_traffic_source))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved traffic_source as @traffic_source" do
        TrafficSource.stub(:new).with({'these' => 'params'}) { mock_traffic_source(:save => false) }
        post :create, :traffic_source => {'these' => 'params'}
        assigns(:traffic_source).should be(mock_traffic_source)
      end

      it "re-renders the 'new' template" do
        TrafficSource.stub(:new) { mock_traffic_source(:save => false) }
        post :create, :traffic_source => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested traffic_source" do
        TrafficSource.stub(:find).with("37") { mock_traffic_source }
        mock_traffic_source.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :traffic_source => {'these' => 'params'}
      end

      it "assigns the requested traffic_source as @traffic_source" do
        TrafficSource.stub(:find) { mock_traffic_source(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:traffic_source).should be(mock_traffic_source)
      end

      it "redirects to the traffic_source" do
        TrafficSource.stub(:find) { mock_traffic_source(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(traffic_source_url(mock_traffic_source))
      end
    end

    describe "with invalid params" do
      it "assigns the traffic_source as @traffic_source" do
        TrafficSource.stub(:find) { mock_traffic_source(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:traffic_source).should be(mock_traffic_source)
      end

      it "re-renders the 'edit' template" do
        TrafficSource.stub(:find) { mock_traffic_source(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested traffic_source" do
      TrafficSource.stub(:find).with("37") { mock_traffic_source }
      mock_traffic_source.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the traffic_sources list" do
      TrafficSource.stub(:find) { mock_traffic_source }
      delete :destroy, :id => "1"
      response.should redirect_to(traffic_sources_url)
    end
  end

end
